name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly
      placeholder: "When I click X, Y happens instead of Z"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug
      placeholder: |
        1. Open the route window with /qr
        2. Click on ...
        3. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: QuickRoute version
      description: "If you can't paste debug info above, enter the version manually"
      placeholder: "1.0.0"
  - type: textarea
    id: debug_info
    attributes:
      label: Debug info
      description: |
        Click **Copy Debug** in the QuickRoute window (or type `/qrdebug copy`), then paste here.
        The output is pre-formatted markdown — just paste it as-is.
      render: markdown
  - type: textarea
    id: lua_errors
    attributes:
      label: Lua errors (if any)
      description: Paste any error messages from BugSack/BugGrabber
      render: text
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, other addons that might conflict, etc.
