name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or frustration
      placeholder: "I often need to get to X but there's no quick way to..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New teleport / portal
        - Routing / pathfinding
        - User interface
        - Integration (TomTom, map, quest tracker)
        - Settings / configuration
        - Other
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, mockups, links to Wowhead, etc.
