-- FlightPoints.lua
-- Zones with a flight master, and the position of one of their flight points
-- in both zone and world coordinates.
--
-- GENERATED by scripts/generate_flight_points.py -- do not edit by hand.
--
-- Derived from the client's own tables, not surveyed. TaxiNodes gives every
-- taxi node with a world position and the world map it sits on, TaxiPath gives
-- the network between them, and UiMapAssignment converts a world position into
-- a zone with normalized coordinates.
--
-- Five filters, because TaxiNodes holds far more than flight masters. A node
-- is kept only when it has at least two TaxiPath neighbours (a flight master
-- connects to many nodes; a scripted quest flight to one, and the boat and
-- zeppelin nodes to none), is not tagged internal or disabled, is shown to
-- players by its Flags, sits inside some zone-type UiMap box, and -- if its
-- name states a zone at all -- states the zone the geometry put it in.
--
-- A name of the form "Place, Zone" has to agree with the geometry: zone boxes
-- overlap at borders, and without that test "New Kargath, Badlands" lands in
-- Searing Gorge 1103 yards away. A name with no comma states no zone, so it
-- neither confirms nor contradicts: those are kept, but rank below a name that
-- does confirm. That is what makes Broken Shore pick "Vengeance Point, Broken
-- Shore" over the bare "Dalaran" sitting 1332 yards from it.
--
-- One entry per zone: a corroborating name first, then the most connected
-- node, then the lowest node ID so regeneration is stable. The graph is
-- zone-level, and from any flight master the game auto-routes multi-hop to
-- every point you have discovered on that world map.
--
-- x and y are normalized ZONE coordinates, and the UI axes are the transpose
-- of the world axes with both running backwards -- see project() in the
-- generator for the evidence. Getting that backwards put Stormwind's flight
-- master 918 yards from where it stands, and the "inside the unit square"
-- check could not see it, because a swapped and mirrored unit square is still
-- the unit square.
--
-- worldX/worldY are what edge weights are computed from: the distance is
-- exact, and only the speed it is divided by is an estimate. continentID is
-- the world map from TaxiNodes, NOT a uiMapID. It is necessary for two zones
-- to be connected by flight but not sufficient -- world map 530 holds Outland
-- AND the Burning Crusade starting zones, which are not one taxi network, so
-- PathCalculator requires the addon's own continent to agree as well.
local ADDON_NAME, QR = ...

QR.FlightPoints = {
    -- world map 0
    [14] = { x = 0.3992, y = 0.4739, worldX = -1240.5, worldY = -2515.1, node = "Refuge Pointe, Arathi", continentID = 0, faction = "Alliance", alt = { x = 0.6815, y = 0.3341, worldX = -916.3, worldY = -3496.9, node = "Hammerfall, Arathi", continentID = 0, faction = "Horde" } },
    [15] = { x = 0.6425, y = 0.3523, worldX = -6574.9, worldY = -3875.1, node = "Fuselight, Badlands", continentID = 0, faction = "both" },
    [17] = { x = 0.4711, y = 0.8922, worldX = -12761.9, worldY = -2919.0, node = "Surwich, Blasted Lands", continentID = 0, faction = "Alliance", alt = { x = 0.5091, y = 0.7267, worldX = -12357.6, worldY = -3058.2, node = "Sunveil Excursion, Blasted Lands", continentID = 0, faction = "Horde" } },
    [21] = { x = 0.4556, y = 0.4242, worldX = 478.9, worldY = 1536.6, node = "The Sepulcher, Silverpine Forest", continentID = 0, faction = "Horde" },
    [22] = { x = 0.4295, y = 0.8495, worldX = 931.3, worldY = -1430.1, node = "Chillwind Camp, Western Plaguelands", continentID = 0, faction = "Alliance", alt = { x = 0.5052, y = 0.5241, worldX = 1864.3, worldY = -1755.8, node = "The Menders' Stead, Western Plaguelands", continentID = 0, faction = "Horde" } },
    [23] = { x = 0.7574, y = 0.5332, worldX = 2271.1, worldY = -5340.8, node = "Light's Hope Chapel, Eastern Plaguelands", continentID = 0, faction = "Alliance", alt = { x = 0.7580, y = 0.5336, worldX = 2270.2, worldY = -5343.1, node = "Light's Hope Chapel, Eastern Plaguelands", continentID = 0, faction = "Horde" } },
    [25] = { x = 0.5602, y = 0.4624, worldX = -17.7, worldY = -874.2, node = "Tarren Mill, Hillsbrad", continentID = 0, faction = "Horde" },
    [26] = { x = 0.1111, y = 0.4609, worldX = 283.7, worldY = -2002.8, node = "Aerie Peak, The Hinterlands", continentID = 0, faction = "Alliance", alt = { x = 0.8170, y = 0.8189, worldX = -635.3, worldY = -4720.5, node = "Revantusk Village, The Hinterlands", continentID = 0, faction = "Horde" } },
    [27] = { x = 0.7587, y = 0.5429, worldX = -5714.1, worldY = -1578.6, node = "Gol'Bolar Quarry, Dun Morogh", continentID = 0, faction = "Alliance" },
    [32] = { x = 0.3789, y = 0.3043, worldX = -6552.6, worldY = -1168.3, node = "Thorium Point, Searing Gorge", continentID = 0, faction = "Alliance", alt = { x = 0.3483, y = 0.3058, worldX = -6554.9, worldY = -1100.1, node = "Thorium Point, Searing Gorge", continentID = 0, faction = "Horde" } },
    [36] = { x = 0.7214, y = 0.6568, worldX = -8364.6, worldY = -2738.4, node = "Morgan's Vigil, Burning Steppes", continentID = 0, faction = "Alliance", alt = { x = 0.1780, y = 0.5271, worldX = -8092.3, worldY = -1025.8, node = "Flamestar Post, Burning Steppes", continentID = 0, faction = "Horde" } },
    [37] = { x = 0.4178, y = 0.6456, worldX = -9434.0, worldY = 85.1, node = "Goldshire, Elwynn", continentID = 0, faction = "Alliance" },
    [47] = { x = 0.2097, y = 0.5672, worldX = -10737.6, worldY = 267.0, node = "Raven Hill, Duskwood", continentID = 0, faction = "Alliance" },
    [48] = { x = 0.3394, y = 0.5079, worldX = -5421.9, worldY = -2930.0, node = "Thelsamar, Loch Modan", continentID = 0, faction = "Alliance" },
    [49] = { x = 0.2928, y = 0.5340, worldX = -9429.1, worldY = -2231.4, node = "Lakeshire, Redridge", continentID = 0, faction = "Alliance" },
    [50] = { x = 0.3896, y = 0.5113, worldX = -12414.2, worldY = 146.3, node = "Grom'gol, Stranglethorn", continentID = 0, faction = "Horde" },
    [51] = { x = 0.7214, y = 0.1205, worldX = -9737.1, worldY = -3890.7, node = "Bogpaddle, Swamp of Sorrows", continentID = 0, faction = "both" },
    [52] = { x = 0.5664, y = 0.4937, worldX = -10551.9, worldY = 1034.4, node = "Sentinel Hill, Westfall", continentID = 0, faction = "Alliance" },
    [56] = { x = 0.0939, y = 0.5950, worldX = -3787.8, worldY = -777.7, node = "Menethil Harbor, Wetlands", continentID = 0, faction = "Alliance" },
    [84] = { x = 0.7098, y = 0.7297, worldX = -8841.1, worldY = 489.7, node = "Stormwind, Elwynn", continentID = 0, faction = "Alliance" },
    [87] = { x = 0.5589, y = 0.4787, worldX = -4821.8, worldY = -1155.4, node = "Ironforge, Dun Morogh", continentID = 0, faction = "Alliance" },
    [90] = { x = 0.6309, y = 0.4832, worldX = 1568.6, worldY = 268.0, node = "Undercity, Tirisfal", continentID = 0, faction = "Horde" },
    [210] = { x = 0.4167, y = 0.7435, worldX = -14473.0, worldY = 464.1, node = "Booty Bay, Stranglethorn", continentID = 0, faction = "Alliance", alt = { x = 0.4052, y = 0.7326, worldX = -14444.3, worldY = 509.6, node = "Booty Bay, Stranglethorn", continentID = 0, faction = "Horde" } },
    [217] = { x = 0.5725, y = 0.1796, worldX = -910.2, worldY = 1638.6, node = "Forsaken Forward Command, Gilneas", continentID = 0, faction = "Horde" },
    [241] = { x = 0.7384, y = 0.5281, worldX = -4012.4, worldY = -6329.2, node = "Dragonmaw Port, Twilight Highlands", continentID = 0, faction = "Horde", alt = { x = 0.6038, y = 0.5769, worldX = -4183.9, worldY = -5620.1, node = "Firebeard's Patrol, Twilight Highlands", continentID = 0, faction = "Alliance" } },
    [2393] = { x = 0.5097, y = 0.7102, worldX = 8444.3, worldY = -4765.7, node = "Sanctum of Light, Silvermoon City", continentID = 0, faction = "both" },
    [2395] = { x = 0.3106, y = 0.9005, worldX = 4512.1, worldY = -2780.1, node = "Silverglade Refuge, Eversong Woods", continentID = 0, faction = "Alliance" },
    [2424] = { x = 0.5775, y = 0.3381, worldX = 11245.3, worldY = -4781.4, node = "Terrace of the Sun, Isle of Quel'Danas", continentID = 0, faction = "both" },
    [2437] = { x = 0.3880, y = 0.2318, worldX = 6916.6, worldY = -7114.0, node = "Witherbark Bluffs, Zul'Aman", continentID = 0, faction = "both" },
    [2512] = { x = 0.5788, y = 0.4576, worldX = 6098.5, worldY = -12045.8, node = "Tokka's Landing, The Coiled Isle", continentID = 0, faction = "both" },
    [2536] = { x = 0.4008, y = 0.4116, worldX = 5114.3, worldY = -6473.8, node = "Atal'Aman, Zul'Aman", continentID = 0, faction = "both" },
    -- world map 1
    [1] = { x = 0.5304, y = 0.4364, worldX = 269.9, worldY = -4766.8, node = "Razor Hill, Durotar", continentID = 1, faction = "Horde" },
    [57] = { x = 0.5539, y = 0.8845, worldX = 8383.8, worldY = 981.0, node = "Rut'theran Village, Teldrassil", continentID = 1, faction = "Alliance" },
    [62] = { x = 0.5172, y = 0.1770, worldX = 7459.9, worldY = -326.6, node = "Lor'danel, Darkshore", continentID = 1, faction = "Alliance" },
    [63] = { x = 0.3450, y = 0.4802, worldX = 2827.3, worldY = -289.2, node = "Astranaar, Ashenvale", continentID = 1, faction = "Alliance", alt = { x = 0.7326, y = 0.6167, worldX = 2302.4, worldY = -2524.6, node = "Splintertree Post, Ashenvale", continentID = 1, faction = "Horde" } },
    [64] = { x = 0.1122, y = 0.1173, worldX = -4310.6, worldY = -927.1, node = "Westreach Summit, Thousand Needles", continentID = 1, faction = "Horde", alt = { x = 0.7909, y = 0.7189, worldX = -6075.4, worldY = -3913.4, node = "Fizzle & Pozzik's Speedbarge, Thousand Needles", continentID = 1, faction = "Alliance" } },
    [65] = { x = 0.3202, y = 0.6179, worldX = 973.9, worldY = 2013.1, node = "Farwatcher's Glen, Stonetalon Mountains", continentID = 1, faction = "Alliance" },
    [66] = { x = 0.6467, y = 0.1044, worldX = 139.2, worldY = 1325.8, node = "Nijel's Point, Desolace", continentID = 1, faction = "Alliance", alt = { x = 0.2156, y = 0.7404, worldX = -1767.6, worldY = 3263.9, node = "Shadowprey Village, Desolace", continentID = 1, faction = "Horde" } },
    [69] = { x = 0.7543, y = 0.4431, worldX = -4419.9, worldY = 199.3, node = "Camp Mojache, Feralas", continentID = 1, faction = "Horde", alt = { x = 0.4681, y = 0.4533, worldX = -4467.0, worldY = 2188.6, node = "Feathermoon, Feralas", continentID = 1, faction = "Alliance" } },
    [70] = { x = 0.6746, y = 0.5120, worldX = -3825.4, worldY = -4516.6, node = "Theramore, Dustwallow Marsh", continentID = 1, faction = "Alliance", alt = { x = 0.3557, y = 0.3183, worldX = -3147.4, worldY = -2842.2, node = "Brackenwall Village, Dustwallow Marsh", continentID = 1, faction = "Horde" } },
    [71] = { x = 0.5201, y = 0.2752, worldX = -7094.0, worldY = -3813.7, node = "Gadgetzan, Tanaris", continentID = 1, faction = "Horde", alt = { x = 0.5138, y = 0.2943, worldX = -7186.0, worldY = -3768.2, node = "Gadgetzan, Tanaris", continentID = 1, faction = "Alliance" } },
    [76] = { x = 0.5298, y = 0.4988, worldX = 3547.2, worldY = -6294.7, node = "Bilgewater Harbor, Azshara", continentID = 1, faction = "Horde" },
    [77] = { x = 0.6057, y = 0.2532, worldX = 6214.3, worldY = -1874.3, node = "Talonbranch Glade, Felwood", continentID = 1, faction = "Alliance", alt = { x = 0.4359, y = 0.2868, worldX = 6078.5, worldY = -845.0, node = "Whisperwind Grove, Felwood", continentID = 1, faction = "Horde" } },
    [78] = { x = 0.5607, y = 0.6411, worldX = -7548.0, worldY = -1541.1, node = "Marshal's Stand, Un'Goro Crater", continentID = 1, faction = "both" },
    [80] = { x = 0.4791, y = 0.6711, worldX = 7458.5, worldY = -2487.2, node = "Moonglade", continentID = 1, faction = "Alliance", alt = { x = 0.3215, y = 0.6633, worldX = 7470.4, worldY = -2123.4, node = "Moonglade", continentID = 1, faction = "Horde" } },
    [81] = { x = 0.5289, y = 0.3468, worldX = -6811.4, worldY = 836.7, node = "Cenarion Hold, Silithus", continentID = 1, faction = "Horde", alt = { x = 0.5449, y = 0.3285, worldX = -6761.8, worldY = 772.0, node = "Cenarion Hold, Silithus", continentID = 1, faction = "Alliance" } },
    [83] = { x = 0.5885, y = 0.4831, worldX = 6813.1, worldY = -4611.1, node = "Everlook, Winterspring", continentID = 1, faction = "Horde", alt = { x = 0.6099, y = 0.4871, worldX = 6796.8, worldY = -4742.4, node = "Everlook, Winterspring", continentID = 1, faction = "Alliance" } },
    [85] = { x = 0.4927, y = 0.5937, worldX = 1798.3, worldY = -4363.3, node = "Orgrimmar, Durotar", continentID = 1, faction = "Horde" },
    [88] = { x = 0.4665, y = 0.4990, worldX = -1197.2, worldY = 29.7, node = "Thunder Bluff, Mulgore", continentID = 1, faction = "Horde" },
    [89] = { x = 0.3672, y = 0.4827, worldX = 9968.8, worldY = 2622.1, node = "Darnassus, Teldrassil", continentID = 1, faction = "Alliance" },
    [198] = { x = 0.6219, y = 0.2161, worldX = 5584.1, worldY = -3569.8, node = "Nordrassil, Hyjal", continentID = 1, faction = "both" },
    [249] = { x = 0.5626, y = 0.3356, worldX = -9415.0, worldY = -1043.0, node = "Ramkahen, Uldum", continentID = 1, faction = "both" },
    -- world map 530
    [94] = { x = 0.4399, y = 0.6993, worldX = 8745.8, worldY = -6654.1, node = "Fairbreeze Village, Eversong Woods", continentID = 530, faction = "Horde" },
    [95] = { x = 0.4548, y = 0.3055, worldX = 7594.5, worldY = -6784.3, node = "Tranquillien, Ghostlands", continentID = 530, faction = "Horde", alt = { x = 0.7467, y = 0.6713, worldX = 6789.8, worldY = -7747.6, node = "Zul'Aman, Ghostlands", continentID = 530, faction = "Alliance" } },
    [100] = { x = 0.2785, y = 0.6007, worldX = -587.4, worldY = 4101.0, node = "Falcon Watch, Hellfire Peninsula", continentID = 530, faction = "Horde", alt = { x = 0.5465, y = 0.6257, worldX = -673.4, worldY = 2717.3, node = "Honor Hold, Hellfire Peninsula", continentID = 530, faction = "Alliance" } },
    [102] = { x = 0.6786, y = 0.5136, worldX = 213.8, worldY = 6063.8, node = "Telredor, Zangarmarsh", continentID = 530, faction = "Alliance", alt = { x = 0.3300, y = 0.5119, worldX = 219.4, worldY = 7816.0, node = "Zabra'jin, Zangarmarsh", continentID = 530, faction = "Horde" } },
    [103] = { x = 0.5439, y = 0.3659, worldX = -3867.6, worldY = -11641.1, node = "The Exodar", continentID = 530, faction = "Alliance" },
    [104] = { x = 0.6319, y = 0.3048, worldX = -3065.6, worldY = 749.4, node = "Altar of Sha'tar, Shadowmoon Valley", continentID = 530, faction = "both" },
    [105] = { x = 0.3781, y = 0.6151, worldX = 2183.6, worldY = 6794.5, node = "Sylvanaar, Blade's Edge Mountains", continentID = 530, faction = "Alliance", alt = { x = 0.5207, y = 0.5425, worldX = 2446.4, worldY = 6020.9, node = "Thunderlord Stronghold, Blade's Edge Mountains", continentID = 530, faction = "Horde" } },
    [107] = { x = 0.5413, y = 0.7522, worldX = -2729.0, worldY = 7305.3, node = "Telaar, Nagrand", continentID = 530, faction = "Alliance" },
    [108] = { x = 0.5945, y = 0.5520, worldX = -2987.2, worldY = 3872.8, node = "Allerian Stronghold, Terokkar Forest", continentID = 530, faction = "Alliance", alt = { x = 0.4925, y = 0.4354, worldX = -2567.3, worldY = 4423.8, node = "Stonebreaker Hold, Terokkar Forest", continentID = 530, faction = "Horde" } },
    [109] = { x = 0.4527, y = 0.3494, worldX = 4157.6, worldY = 2959.7, node = "The Stormspire, Netherstorm", continentID = 530, faction = "both" },
    [110] = { x = 0.6316, y = 0.9649, worldX = 9375.2, worldY = -7165.9, node = "Silvermoon City", continentID = 530, faction = "Horde" },
    [111] = { x = 0.6380, y = 0.4172, worldX = -1837.2, worldY = 5301.9, node = "Shattrath, Terokkar Forest", continentID = 530, faction = "both" },
    [122] = { x = 0.4828, y = 0.2506, worldX = 13012.7, worldY = -6908.4, node = "Shattered Sun Staging Area", continentID = 530, faction = "both" },
    -- world map 571
    [114] = { x = 0.5893, y = 0.6838, worldX = 2269.5, worldY = 5173.7, node = "Valiance Keep, Borean Tundra", continentID = 571, faction = "Alliance", alt = { x = 0.4038, y = 0.5145, worldX = 2920.3, worldY = 6242.9, node = "Warsong Hold, Borean Tundra", continentID = 571, faction = "Horde" } },
    [115] = { x = 0.7655, y = 0.6236, worldX = 3243.0, worldY = -666.2, node = "Venomspite, Dragonblight", continentID = 571, faction = "Horde", alt = { x = 0.7706, y = 0.4981, worldX = 3712.4, worldY = -694.9, node = "Wintergarde Keep, Dragonblight", continentID = 571, faction = "Alliance" } },
    [116] = { x = 0.6495, y = 0.4687, worldX = 3876.3, worldY = -4520.1, node = "Camp Oneqwah, Grizzly Hills", continentID = 571, faction = "Horde", alt = { x = 0.3131, y = 0.5915, worldX = 3446.4, worldY = -2754.1, node = "Amberpine Lodge, Grizzly Hills", continentID = 571, faction = "Alliance" } },
    [117] = { x = 0.3126, y = 0.4400, worldX = 1342.8, worldY = -3287.9, node = "Westguard Keep, Howling Fjord", continentID = 571, faction = "Alliance", alt = { x = 0.5204, y = 0.6736, worldX = 401.1, worldY = -4544.3, node = "New Agamand, Howling Fjord", continentID = 571, faction = "Horde" } },
    [118] = { x = 0.1945, y = 0.4783, worldX = 7427.3, worldY = 4224.2, node = "Death's Rise, Icecrown", continentID = 571, faction = "both" },
    [119] = { x = 0.5007, y = 0.6133, worldX = 5506.2, worldY = 4748.1, node = "River's Heart, Sholazar Basin", continentID = 571, faction = "both" },
    [120] = { x = 0.4451, y = 0.2812, worldX = 8864.7, worldY = -1324.3, node = "Ulduar, The Storm Peaks", continentID = 571, faction = "both" },
    [121] = { x = 0.1406, y = 0.7359, worldX = 5218.9, worldY = -1302.2, node = "Ebon Watch, Zul'Drak", continentID = 571, faction = "both" },
    [123] = { x = 0.7205, y = 0.3105, worldX = 5100.8, worldY = 2185.6, node = "Valiance Landing Camp, Wintergrasp", continentID = 571, faction = "Alliance", alt = { x = 0.2163, y = 0.3487, worldX = 5025.0, worldY = 3685.6, node = "Warsong Camp, Wintergrasp", continentID = 571, faction = "Horde" } },
    [127] = { x = 0.7212, y = 0.8081, worldX = 5035.6, worldY = -520.0, node = "Windrunner's Overlook, Crystalsong Forest", continentID = 571, faction = "Alliance", alt = { x = 0.7848, y = 0.5024, worldX = 5590.5, worldY = -693.2, node = "Sunreaver's Command, Crystalsong Forest", continentID = 571, faction = "Horde" } },
    -- world map 870
    [371] = { x = 0.4703, y = 0.4616, worldX = 1503.7, worldY = -1832.1, node = "Dawn's Blossom, Jade Forest", continentID = 870, faction = "both" },
    [376] = { x = 0.5642, y = 0.5034, worldX = -221.3, worldY = 464.6, node = "Halfhill, Valley of the Four Winds", continentID = 870, faction = "both" },
    [379] = { x = 0.6244, y = 0.8071, worldX = 2250.6, worldY = 931.6, node = "Eastwind Rest, Kun-Lai Summit", continentID = 870, faction = "Horde", alt = { x = 0.6244, y = 0.3009, worldX = 4363.0, worldY = 932.1, node = "Zouchin Village, Kun-Lai Summit", continentID = 870, faction = "Alliance" } },
    [388] = { x = 0.7112, y = 0.5733, worldX = 2363.2, worldY = 2994.4, node = "Longying Outpost, Townlong Steppes", continentID = 870, faction = "both" },
    [418] = { x = 0.2896, y = 0.5041, worldX = -1685.7, worldY = 1590.3, node = "Dawnchaser Retreat, Krasarang Wilds", continentID = 870, faction = "Horde", alt = { x = 0.3124, y = 0.6310, worldX = -2082.3, worldY = 1483.6, node = "Cradle of Chi-Ji, Krasarang Wilds", continentID = 870, faction = "Alliance" } },
    [422] = { x = 0.5582, y = 0.3486, worldX = 172.7, worldY = 3152.2, node = "Klaxxi'vess, Dread Wastes", continentID = 870, faction = "both" },
    [433] = { x = 0.5665, y = 0.7565, worldX = 784.9, worldY = -203.7, node = "Tavern in the Mists, The Veiled Stair", continentID = 870, faction = "both" },
    [507] = { x = 0.4188, y = 0.7923, worldX = 5753.8, worldY = 1255.6, node = "Beeble's Wreck, Isle Of Giants", continentID = 870, faction = "Alliance", alt = { x = 0.5167, y = 0.7538, worldX = 5799.6, worldY = 1080.6, node = "Bozzle's Wreck, Isle Of Giants", continentID = 870, faction = "Horde" } },
    [554] = { x = 0.2316, y = 0.7092, worldX = -901.4, worldY = -4639.1, node = "Tushui Landing, Timeless Isle", continentID = 870, faction = "Alliance" },
    [1530] = { x = 0.6290, y = 0.1919, worldX = 1580.2, worldY = 894.2, node = "Shrine of Two Moons, Vale of Eternal Blossoms", continentID = 870, faction = "Horde", alt = { x = 0.1367, y = 0.7732, worldX = 611.4, worldY = 2125.0, node = "Serpent's Spine, Vale of Eternal Blossoms", continentID = 870, faction = "Alliance" } },
    -- world map 1116
    [525] = { x = 0.4810, y = 0.6613, worldX = 5578.9, worldY = 4564.8, node = "Frostwall Garrison, Frostfire Ridge", continentID = 1116, faction = "Horde", alt = { x = 0.5148, y = 0.2147, worldX = 7399.5, worldY = 4358.4, node = "Bloodmaul Slag Mines, Frostfire Ridge", continentID = 1116, faction = "Alliance" } },
    [534] = { x = 0.2616, y = 0.3897, worldX = 4569.4, worldY = 335.1, node = "Aktar's Post, Tanaan Jungle", continentID = 1116, faction = "both" },
    [535] = { x = 0.5126, y = 0.4282, worldX = 2727.2, worldY = 2777.0, node = "Shattrath City, Talador", continentID = 1116, faction = "both" },
    [539] = { x = 0.4564, y = 0.2539, worldX = 1526.4, worldY = -788.9, node = "Exile's Rise, Shadowmoon Valley", continentID = 1116, faction = "both" },
    [542] = { x = 0.3953, y = 0.4336, worldX = -368.2, worldY = 2285.6, node = "Axefall, Spires of Arak", continentID = 1116, faction = "Horde", alt = { x = 0.3901, y = 0.6191, worldX = -1117.4, worldY = 2317.0, node = "Southport, Spires of Arak", continentID = 1116, faction = "Alliance" } },
    [543] = { x = 0.6410, y = 0.5750, worldX = 6456.1, worldY = -174.8, node = "Wildwood Wash, Gorgrond", continentID = 1116, faction = "Alliance", alt = { x = 0.5701, y = 0.4580, worldX = 7093.6, worldY = 404.7, node = "Everbloom Wilds, Gorgrond", continentID = 1116, faction = "Horde" } },
    [550] = { x = 0.8324, y = 0.4460, worldX = 3235.7, worldY = 4584.5, node = "Wor'var, Nagrand", continentID = 1116, faction = "Horde", alt = { x = 0.6357, y = 0.6155, worldX = 2594.2, worldY = 5700.6, node = "Telaari Station, Nagrand", continentID = 1116, faction = "Alliance" } },
    [588] = { x = 0.4065, y = 0.1061, worldX = 5356.2, worldY = -3942.2, node = "Warspear, Ashran", continentID = 1116, faction = "Horde", alt = { x = 0.3739, y = 0.9090, worldX = 3685.1, worldY = -3840.5, node = "Stormshield (Alliance), Ashran", continentID = 1116, faction = "Alliance" } },
    -- world map 1220
    [634] = { x = 0.5200, y = 0.3467, worldX = 3835.6, worldY = 2016.1, node = "Stormtorn Foothills, Stormheim", continentID = 1220, faction = "both" },
    [641] = { x = 0.5496, y = 0.7255, worldX = 2299.9, worldY = 6577.7, node = "Lorlathil, Val'sharah", continentID = 1220, faction = "both" },
    [646] = { x = 0.4974, y = 0.2108, worldX = -545.2, worldY = 3001.8, node = "Vengeance Point, Broken Shore", continentID = 1220, faction = "both" },
    [650] = { x = 0.2997, y = 0.3935, worldX = 5108.3, worldY = 5570.6, node = "Felbane Camp, Highmountain", continentID = 1220, faction = "both" },
    [680] = { x = 0.6422, y = 0.4194, worldX = 1893.3, worldY = 3092.6, node = "Crimson Thicket, Suramar", continentID = 1220, faction = "both" },
    [739] = { x = 0.3646, y = 0.2782, worldX = 4634.3, worldY = 5339.4, node = "Trueshot Lodge, Highmountain", continentID = 1220, faction = "both" },
    [790] = { x = 0.3825, y = 0.4592, worldX = -3362.3, worldY = 4823.0, node = "Eye of Azshara, Azsuna", continentID = 1220, faction = "both" },
    [1187] = { x = 0.5617, y = 0.5896, worldX = -784.2, worldY = 6130.0, node = "Shackle's Den, Azsuna", continentID = 1220, faction = "both" },
    -- world map 1642
    [862] = { x = 0.7045, y = 0.6527, worldX = -2303.2, worldY = -252.9, node = "Seeker's Outpost, Zuldazar", continentID = 1642, faction = "both" },
    [863] = { x = 0.3894, y = 0.7806, worldX = 793.2, worldY = 1400.7, node = "Zul'jan, Nazmir", continentID = 1642, faction = "Horde", alt = { x = 0.3424, y = 0.6330, worldX = 1310.3, worldY = 1647.5, node = "Grimwatt's Crash, Nazmir", continentID = 1642, faction = "Alliance" } },
    [864] = { x = 0.3973, y = 0.8386, worldX = 528.7, worldY = 3983.1, node = "Deadwood Cove, Vol'dun", continentID = 1642, faction = "Alliance", alt = { x = 0.4726, y = 0.3517, worldX = 2740.2, worldY = 3469.9, node = "Vorrik's Sanctum, Vol'dun", continentID = 1642, faction = "Horde" } },
    [1165] = { x = 0.5165, y = 0.4121, worldX = -1036.0, worldY = 756.6, node = "The Great Seal", continentID = 1642, faction = "Horde" },
    -- world map 1643
    [895] = { x = 0.7578, y = 0.4865, worldX = -93.7, worldY = -633.3, node = "Bridgeport, Tiragarde Sound", continentID = 1643, faction = "Alliance", alt = { x = 0.8640, y = 0.8091, worldX = -1688.0, worldY = -1420.5, node = "Castaway Point, Tiragarde Sound", continentID = 1643, faction = "Horde" } },
    [896] = { x = 0.7105, y = 0.4083, worldX = -297.0, worldY = 1227.5, node = "Hangman's Point, Drustvar", continentID = 1643, faction = "Alliance", alt = { x = 0.2570, y = 0.1654, worldX = 632.0, worldY = 3829.4, node = "Whitegrove Chapel, Drustvar", continentID = 1643, faction = "Horde" } },
    [942] = { x = 0.4008, y = 0.3727, worldX = 3752.6, worldY = 1068.6, node = "Seekers Vista, Stormsong Valley", continentID = 1643, faction = "both" },
    [1169] = { x = 0.3799, y = 0.9199, worldX = -80.0, worldY = -2648.4, node = "Tol Dagor, Tiragarde Sound", continentID = 1643, faction = "Alliance", alt = { x = 0.2325, y = 0.4654, worldX = 139.7, worldY = -2541.4, node = "Tol Dagor, Tiragarde Sound", continentID = 1643, faction = "Horde" } },
    [1462] = { x = 0.7360, y = 0.2562, worldX = 3282.0, worldY = 4900.5, node = "Prospectus Bay, Mechagon", continentID = 1643, faction = "Horde", alt = { x = 0.7786, y = 0.4087, worldX = 3044.4, worldY = 4800.8, node = "Overspark Expedition Camp, Mechagon", continentID = 1643, faction = "Alliance" } },
    -- world map 1669
    [830] = { x = 0.6199, y = 0.8691, worldX = 501.3, worldY = 1470.3, node = "Vindicaar, Krokuun", continentID = 1669, faction = "both" },
    [882] = { x = 0.5166, y = 0.8718, worldX = 4728.6, worldY = 9862.5, node = "Vindicaar, Eredath", continentID = 1669, faction = "both" },
    [885] = { x = 0.7586, y = 0.3735, worldX = -2636.1, worldY = 8699.9, node = "Vindicaar, Antoran Wastes", continentID = 1669, faction = "both" },
    -- world map 1718
    [1355] = { x = 0.7420, y = 0.2495, worldX = 2077.9, worldY = -1566.3, node = "Kelya's Grave, Nazjatar", continentID = 1718, faction = "both" },
    -- world map 2222
    [1525] = { x = 0.6053, y = 0.6077, worldX = -2624.0, worldY = 6010.5, node = "Darkhaven, Revendreth", continentID = 2222, faction = "both" },
    [1536] = { x = 0.4997, y = 0.5324, worldX = 2580.5, worldY = -2520.8, node = "Theater of Pain, Maldraxxus", continentID = 2222, faction = "both" },
    [1565] = { x = 0.4639, y = 0.5105, worldX = -6788.6, worldY = 1006.8, node = "Heart of the Forest, Ardenweald", continentID = 2222, faction = "both" },
    [1569] = { x = 0.4409, y = 0.3245, worldX = -2305.1, worldY = -4361.4, node = "Sagehaven, Bastion", continentID = 2222, faction = "both" },
    -- world map 2374
    [1970] = { x = 0.3561, y = 0.6504, worldX = -4213.0, worldY = 684.6, node = "Haven, Zereth Mortis", continentID = 2374, faction = "both" },
    -- world map 2444
    [2022] = { x = 0.5781, y = 0.6803, worldX = 1753.2, worldY = 42.1, node = "Ruby Life Pools, The Waking Shores", continentID = 2444, faction = "both" },
    [2023] = { x = 0.6301, y = 0.4215, worldX = -706.5, worldY = 2048.9, node = "Maruukai, Ohn'ahran Plains", continentID = 2444, faction = "both" },
    [2024] = { x = 0.4674, y = 0.3959, worldX = -3801.0, worldY = 404.5, node = "Camp Antonidas, Azure Span", continentID = 2444, faction = "both" },
    [2025] = { x = 0.5111, y = 0.6703, worldX = -318.0, worldY = -2056.0, node = "Gelikyr Post, Thaldraszus", continentID = 2444, faction = "both" },
    [2112] = { x = 0.4447, y = 0.6791, worldX = -10.0, worldY = -844.2, node = "Valdrakken, Thaldraszus", continentID = 2444, faction = "both" },
    [2151] = { x = 0.3574, y = 0.5918, worldX = 6407.7, worldY = -2560.3, node = "Morqut Village, The Forbidden Reach", continentID = 2444, faction = "both" },
    -- world map 2454
    [2133] = { x = 0.4031, y = 0.6789, worldX = -959.3, worldY = 3140.2, node = "Dragonscale Camp, Zaralek Cavern", continentID = 2454, faction = "both" },
    -- world map 2548
    [2200] = { x = 0.5106, y = 0.6241, worldX = -1716.3, worldY = 7074.1, node = "Central Encampment, The Emerald Dream", continentID = 2548, faction = "both" },
    -- world map 2552
    [2271] = { x = 0.3822, y = 0.7853, worldX = 985.5, worldY = -1847.6, node = "Freywold Village, Isle of Dorn", continentID = 2552, faction = "both" },
    [2339] = { x = 0.4476, y = 0.5104, worldX = 2585.4, worldY = -2473.3, node = "Dornogal, Isle of Dorn", continentID = 2552, faction = "both" },
    -- world map 2601
    [2255] = { x = 0.2320, y = 0.5114, worldX = -796.0, worldY = 876.1, node = "Wildcamp Or'lay, Azj-Kahet", continentID = 2601, faction = "both" },
    [2272] = { x = 0.3843, y = 0.3435, worldX = 2224.3, worldY = -2735.8, node = "Gundargaz, The Ringing Deeps", continentID = 2601, faction = "both" },
    [2273] = { x = 0.5439, y = 0.8010, worldX = 1552.8, worldY = 10.9, node = "Lightspark, Hallowfall", continentID = 2601, faction = "both" },
    -- world map 2694
    [2480] = { x = 0.6936, y = 0.5260, worldX = -128.2, worldY = -1673.3, node = "Har'athir, Harandar", continentID = 2694, faction = "both" },
    -- world map 2706
    [2346] = { x = 0.4293, y = 0.4620, worldX = 65.6, worldY = 535.8, node = "The Incontinental Hotel", continentID = 2706, faction = "both" },
    -- world map 2735
    [2352] = { x = 0.4335, y = 0.4497, worldX = 3146.4, worldY = 599.0, node = "Small Aerie, Founder's Point", continentID = 2735, faction = "both" },
    -- world map 2736
    [2351] = { x = 0.5918, y = 0.7189, worldX = 1067.3, worldY = -169.3, node = "The Bloom, Razorwind Shores", continentID = 2736, faction = "both" },
    -- world map 2738
    [2371] = { x = 0.6055, y = 0.2910, worldX = 1610.1, worldY = 227.2, node = "Shan'dorah, K'aresh", continentID = 2738, faction = "both" },
    [2472] = { x = 0.4695, y = 0.5722, worldX = -1206.7, worldY = -217.3, node = "Tazavesh, the Veiled Market", continentID = 2738, faction = "both" },
    -- world map 2771
    [2405] = { x = 0.3690, y = 0.5890, worldX = 1661.9, worldY = 1050.3, node = "The Ingress, Voidstorm", continentID = 2771, faction = "both" },
    -- world map 3047
    [2599] = { x = 0.6080, y = 0.1602, worldX = -3848.8, worldY = 445.9, node = "Umbral Base Camp", continentID = 3047, faction = "both" },
    -- world map 3075
    [2600] = { x = 0.4667, y = 0.8290, worldX = -2180.0, worldY = -1709.0, node = "Umbral Base Camp", continentID = 3075, faction = "both" },
}
